### ISSUE TITLE
AttributeError: module 'dal.autocomplete' has no attribute 'Select2ListView'

### ISSUE THREAD

**Issue by nickmoreton** [cfpb/wagtail-inventory#71]
I was using the latest version 2.0.0 while upgrading an existing site to Wagtail v4.2.1

I noticed that when running the site is saw this error:

```
Traceback (most recent call last):
  File "./manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/test.py", line 23, in run_from_argv
    super().run_from_argv(argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/test.py", line 55, in handle
    failures = test_runner.run_tests(test_labels)
  File "/usr/local/lib/python3.8/site-packages/django/test/runner.py", line 728, in run_tests
    self.run_checks(databases)
  File "/usr/local/lib/python3.8/site-packages/django/test/runner.py", line 665, in run_checks
    call_command('check', verbosity=self.verbosity, databases=databases)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/check.py", line 63, in handle
    self.check(
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 419, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.8/site-packages/django/core/checks/registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 416, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 602, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 595, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/ousweb/urls.py", line 10, in <module>
    from wagtail.admin import urls as wagtailadmin_urls
  File "/usr/local/lib/python3.8/site-packages/wagtail/admin/urls/__init__.py", line 13, in <module>
    from wagtail.admin.api import urls as api_urls
  File "/usr/local/lib/python3.8/site-packages/wagtail/admin/api/urls.py", line 11, in <module>
    for fn in hooks.get_hooks("construct_admin_api"):
  File "/usr/local/lib/python3.8/site-packages/wagtail/hooks.py", line 112, in get_hooks
    search_for_hooks()
  File "/usr/local/lib/python3.8/site-packages/wagtail/hooks.py", line 106, in search_for_hooks
    list(get_app_submodules("wagtail_hooks"))
  File "/usr/local/lib/python3.8/site-packages/wagtail/utils/apps.py", line 23, in get_app_submodules
    yield name, import_module("%s.%s" % (name, submodule_name))
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.8/site-packages/wagtailinventory/wagtail_hooks.py", line 11, in <module>
    from wagtailinventory.views import (
  File "/usr/local/lib/python3.8/site-packages/wagtailinventory/views.py", line 11, in <module>
    class BlockAutocompleteView(autocomplete.Select2ListView):
AttributeError: module 'dal.autocomplete' has no attribute 'Select2ListView'
```
I was upgrading wagtail-inventory from 1.6.0

The solution was to pin the wagtail-inventory requirement to 1.7.0

**Comment by willbarton** [comment]
@nickmoreton 2.0 introduced django-autocomplete-light as a requirement, do you [have `dal` and `dal_select2` in `INSTALLED_APPS`](https://github.com/cfpb/wagtail-inventory#setup)?

If not (it I know this is the error you'll see if `dal_select2` isn't there), we [have some notes in the release](https://github.com/cfpb/wagtail-inventory/releases/tag/2.0.0) about upgrading, hopefully that helps!

If so, we can dig into the issue further.

**Comment by chosak** [comment]
Closing this since as of #84 this package no longer depends on django-autocomplete-light.
